name: A workflow for my "Hello World" file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: [ubuntu-latest, macos-latest, windows-latest]    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Ritwick Bhargav"
